name: Bazel CPP Tests

on:
  workflow_run:
    workflows: ["Bazel Build"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Bazelisk
      uses: bazelbuild/setup-bazelisk@v3

    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: bazel-${{ runner.os }}-build

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libtinfo6

    - name: Clone tree-sitter language repo
      run: |
        git clone https://github.com/tree-sitter/tree-sitter.git
        git clone https://github.com/tree-sitter/tree-sitter-cpp.git

    - name: Setup build
      run: |
        mv build-support/tree-sitter.bazel tree-sitter/BUILD.bazel
        mv build-support/tree-sitter-cpp.bazel tree-sitter-cpp/BUILD.bazel


    - name: Run HHDS tests 
      run: bazel test //hhds:all

