name: Bazel Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Bazelisk
      uses: bazelbuild/setup-bazelisk@v3

    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: bazel-${{ runner.os }}-build

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libtinfo6

    - name: Clone tree-sitter  language repo
      run: |
        git clone https://github.com/tree-sitter/tree-sitter.git
        git clone https://github.com/tree-sitter/tree-sitter-cpp.git

    - name: Setup build
      run: |
        mv build-support/tree-sitter.bazel tree-sitter/BUILD.bazel
        mv build-support/tree-sitter-cpp.bazel tree-sitter-cpp/BUILD.bazel

    - name: Bazel build representative
      run: bazel build --sandbox_debug --verbose_failures //hhds:build_representative_bench
      working-directory: ${{ github.workspace }}

    - name: List Bazel Sandbox Contents
      run: |
        find /home/runner/.cache/bazel/ -type d -name 'execroot' -exec find {} \; | head -n 1000


    - name: Run Bazel build
      run: bazel build //hhds:all

